// Code generated by go generate; DO NOT EDIT.
package main

var SyncHashes = map[string]struct{}{
	"2244ceb986b68c7126bb9f4c69f8da23b649d4d1": struct{}{}, // Link to the Past.lua
	"67599396ae93c008cb34ca5977ece7b9b283e195": struct{}{}, // Metroid Zero Mission.lua
	"55b58ad15c21c58a3b47d62c7b3fee70f8d75978": struct{}{}, // Ocarina of Time.lua
}
