// Code generated by go generate; DO NOT EDIT.
package main

var SyncHashes = map[string]struct{}{
	"690dc6535403582d01e6305867c7eeacfe6730c7": struct{}{}, // Link to the Past.lua
	"594b57b15ff8deb7a9a6eb305c49543a937e67eb": struct{}{}, // Metroid Zero Mission.lua
	"38bd46e9ad6ac064a58528e2bc5da0f787282377": struct{}{}, // Ocarina of Time.lua
}
